platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup_src
- name: gpbackup-go-components
- name: ddboost_components
- name: gpbackup-release-license

outputs:
- name: gpbackup_tar

run:
  path: gpbackup_src/ci/scripts/build-os-tars.bash
