platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup_src
- name: gpdb_src
- name: bin_gpdb
- name: gpbackup_tar
- name: gpbackup-tools-versions

outputs:
- name: gppkgs

params:
  OS:

run:
  path: gpbackup_src/ci/scripts/build-gppkgs.bash
