platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup_src
- name: ccp_src
- name: cluster_env_files
- name: gpdb_src
- name: sqldump

outputs:
- name: artifacts

run:
  path: gpbackup_src/ci/scripts/gpbackup-regression.bash
