platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup_src
- name: ccp_src
- name: cluster_env_files
- name: dummy_seclabel
  optional: true
- name: gppkgs

params:
  default_ami_user: root
  OS:

run:
  path: gpbackup_src/ci/scripts/gpbackup-tests.bash
