platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup_src
- name: ccp_src
- name: cluster_env_files
- name: gpdb_src
- name: backup_artifact_resource
- name: regression_dump

run:
  path: gpbackup_src/ci/scripts/gprestore-regression.bash
