platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup_src
- name: ccp_src
- name: cluster_env_files
- name: gpbackup_1.12.1_dependencies
- name: gpdb_src
- name: bin_gpdb

params:
  GPBACKUP_VERSION:

run:
  path: gpbackup_src/ci/scripts/integration-tests-fixed-version.bash
