platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup_src
- name: gpdb_src
- name: github_release_components
- name: bin_gpdb
- name: gpdb43_backup

run:
  path: gpbackup_src/ci/scripts/restore-to-GPDB6.bash
