platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup_src
- name: ccp_src
- name: cluster_env_files
- name: gppkgs

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BUCKET:
  REGION:
  OS: RHEL

run:
  path: gpbackup_src/ci/scripts/s3-plugin-tests.bash
