platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup_src
- name: ccp_src
- name: cluster_env_files
- name: scale_schema
- name: gppkgs

params:
  OS: RHEL

run:
  path: gpbackup_src/ci/scripts/scale-tests.bash
