platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup_src
- name: gpdb_src
- name: bin_gpdb
- name: gpbackup_manager_src
  path: gp-backup-manager
- name: gppkgs

run:
  path: gpbackup_src/ci/scripts/test-gpbackup-manager.bash
