platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup_src
- name: gpdb_src
- name: bin_gpdb
- name: dummy_seclabel
  optional: true
- name: gppkgs

params:
  REQUIRES_DUMMY_SEC:
  OS: RHEL

run:
  path: gpbackup_src/ci/scripts/test-on-local-cluster.bash
