platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup_src
- name: github_release_components_rc
- name: gpbackup-release-license
- name: pivnet_release_cache
- name: gppkgs

outputs:
- name: workspace

run:
  path: gpbackup_src/ci/scripts/update-metadata.bash
